songs_to_fetch = 5
artists = [
    "A$AP Rocky",
    "Lil Uzi Vert",
    "Playboi Carti",
    "Future",
    "Young Thug",
    "Chance the Rapper",
    "21 Savage",
    "Lil Wayne",
    "Drake",
    "Travis Scott",
    "Juice WRLD",
    "J. Cole",
    "Lil Baby",
    "Kendrick Lamar",
    "Roddy Ricch",
    "Meek Mill",
    "Kanye West",
    "JAY-Z",
    "Isaiah Rashad",
    "Eminem",
    "Pop Smoke",
    "Lil Durk",
    "Gunna",
    "Trippie Redd",
    "Kid Cudi",
    "Pusha T",
    "Earl Sweatshirt",
    "Tyler, The Creator",
    "Big Sean",
    "Yeat",
    "Don Toliver",
    "Migos",
    "Action Bronson"
]