[spotify_credentials]
SPOTIFY_CLIENT_ID = 'accd0aa479164ddcbf1cbf822512b80b'
SPOTIFY_CLIENT_SECRET = '58bfc467435045e7b61c86fb03385729'


[genius_credentials]
GENIUS_CLIENT_ID = '6ik7FFRHyv94azwRfLlDIpTAS-710CM1BoWDfO2x82LkpIz9g9Oo5-YQbp_B_xzA'
GENIUS_CLIENT_SECRET = '23fPMx4U0q6TJRT0ss3aIpXRhT9w0taLUf-3_w2iRxAYU1b3uKSPvucwdqbkf8iObaqM5-_f0RXOTV92bLeLvQ'
GENIUS_ACCESS_TOKEN = 'SFSvR6r7o3-3g123P0DUAFkiqsvBZaptEbjQw2Nw6rAPLUkUA9d89_8VdNa9tK50'


[aws_credentials]
host="hiphopdb.cnbgags9awls.us-east-2.rds.amazonaws.com"
database="hiphop_db"
user="postgres"
password="GullyBull468$"
port="5432"